// Generated by gencpp from file server/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SERVER_MESSAGE_ADDTWOINTS_H
#define SERVER_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <server/AddTwoIntsRequest.h>
#include <server/AddTwoIntsResponse.h>


namespace server
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::server::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::server::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::server::AddTwoInts > {
  static const char* value()
  {
    return "server/AddTwoInts";
  }

  static const char* value(const ::server::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::server::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::server::AddTwoInts >
template<>
struct MD5Sum< ::server::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::server::AddTwoInts >::value();
  }
  static const char* value(const ::server::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::server::AddTwoIntsRequest> should match
// service_traits::DataType< ::server::AddTwoInts >
template<>
struct DataType< ::server::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::server::AddTwoInts >::value();
  }
  static const char* value(const ::server::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::server::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::server::AddTwoInts >
template<>
struct MD5Sum< ::server::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::server::AddTwoInts >::value();
  }
  static const char* value(const ::server::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::server::AddTwoIntsResponse> should match
// service_traits::DataType< ::server::AddTwoInts >
template<>
struct DataType< ::server::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::server::AddTwoInts >::value();
  }
  static const char* value(const ::server::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVER_MESSAGE_ADDTWOINTS_H
